name: ccr
recipe: laravel
config:
  php: "7.4"
  composer_version: 2
  composer: []
  webroot: backend/public
  via: nginx
  config:
    vhosts: .lando/default.conf.tpl
services:
  database:
    config:
      database: .lando/mysql.cnf
  client:
    type: node
    build:
      - cd /app/client && yarn install
    command: cd /app/client && yarn dev
    scanner: false
  appserver:
    build:
      - cd /app/backend && composer install
      - bash /app/.lando/no_env_setup.sh
tooling:
  yarn:
    service: client
    cmd: yarn
  quasar:
    service: client
    cmd: npx quasar
    dir: /app/client
