version: '3'

networks:
  backend:
  frontend:
volumes:
  mysql:
services:
  nginx:
      build:
        context: ./containers/nginx/
        dockerfile: Dockerfile
      environment:
        DHPARAM_SIZE: 1024
        SSL: SNAKEOIL
      ports:
          - "443:443"
      volumes:
          - ./backend:/var/www/html
          - ./data/ssl:/etc/nginx/ssl
      depends_on:
        - phpfpm
        - mysql
        - node
      networks:
        - backend
        - frontend

  mysql:
    image: mysql:5.7.29
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend

  phpfpm:
    env_file:
        - .env
    build:
      context: ./containers/phpfpm
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    networks:
      - backend
    depends_on:
      - mysql

  node:
    build:
      context: ./containers/node
      dockerfile: Dockerfile
    environment:
      APP_NAME: ${APP_NAME}
    volumes: 
      - ./client:/app
    networks:
      - frontend




