name: Deploy Docs
on: 
  push:
    branches:
      - development
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@dev
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: mesh-research/ccr
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: cd docs && yarn && yarn build
        BUILD_DIR: .vuepress/dist/