name: "Meta"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Semantic PR Message
    steps:
      - uses: amannn/action-semantic-pull-request@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
