---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: "Style"

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [development, master]
  pull_request:

###############
# Set the Job #
###############
jobs:
  markdown:
    # Name the Job
    name: Markdown Lint
    # Set the agent to run on
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*(node_modules|vendor).*
          VALIDATE_MARKDOWN: true
          LINTER_RULES_PATH: /
