name: Frontend Testing

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
    - uses: actions/checkout@v2

    - name: Install quasar CLI
      run: yarn global add @quasar/cli
      
    - name: Install dependencies
      run: yarn install

    - name: Build quasar SPA
      run: quasar build -m spa    
