name: Backend Testing

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]
env:
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_PORT: 3306
  DB_DATABASE: homestead
  DB_USERNAME: root
  DB_PASSWORD: root
  APP_ENV: testing
  APP_DEBUG: true
jobs:
  test:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
        with:
          php_version: 7.4

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-node-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Setup Mysql
      run: |
        sudo systemctl start mysql.service
        mysql -uroot -proot -e "CREATE schema $DB_DATABASE;"

      
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Migrate Database
      run: php artisan migrate
    
    - name: Unit Tests
      run: php artisan test
    
